import type { Metadata } from 'next';
import { Archivo_Black, Overpass } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const headerSans = Overpass({
  variable: '--font-overpass',
  subsets: ['latin'],
});

const second = Archivo_Black({
  variable: '--font-archivoblack',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export interface Props {
  children: ReactNode;
}

export default function RootLayout(props: Props) {
  const { children } = props;

  return (
    <html lang="en">
      <body className={`${headerSans.variable} ${second.variable} antialiased`}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
